#!/bin/bash

# Created on 1400/3/31 (2021/6/21).
# Author: [S. Mahdi Mir-Ismaili](https://mirismaili.github.io)
# Based on: https://gist.github.com/linhmtran168/2286aeafe747e78f53bf

# --diff-filter=ACMRTUXB => all changes except "Delete". See: https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---diff-filterACDMRTUXB82308203
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACMRTUXB | grep -E "\\.[jt]sx?$")

if [[ "$STAGED_FILES" == "" ]]; then
	exit 0
fi

# A full list is here: https://gist.github.com/mirismaili/54abf152192205cf615ec1ec90518fd9#file-pre-commit-L13-L36
T="\x1b[0m"   # RESET
B="\x1b[1m"   # BRIGHT
R="\x1b[31m"  # FG_RED
G="\x1b[32m"  # FG_GREEN
W="\x1b[37m"  # FG_WHITE
_R="\x1b[41m" # BG_RED
_G="\x1b[42m" # BG_GREEN

PASS=true

# Check for eslint
PATH=$PWD/node_modules/.bin:$PATH
which eslint &>/dev/null
if [[ "$?" == 1 ]]; then
	echo -e "\t${_R}Please install eslint${T}"
	exit 1
fi

echo -e "\nValidating Javascript:\n"

for FILE in $STAGED_FILES; do
	eslint --max-warnings=0 "$FILE" # "--max-warnings=0" => throws on warnings (like errors)
	RESULT=$?

	if [[ $RESULT == 0 ]]; then
		echo -e "\t${G}ESLint Passed: $FILE${T}"
	else
		echo -e "\t${R}ESLint Failed: $FILE${T}"
		PASS=false
	fi
done

echo -e "\nJavascript validation completed!\n"

if ! $PASS; then
	echo -e "${_R}${W}${B}COMMIT FAILED:\n"
	echo -e "Your commit contains files that should pass ESLint but do not. "
	echo -e "Please fix the ESLint errors and try again.${T}\n"
	exit 1
else
	echo -e "${_G}COMMIT SUCCEEDED${T}\n"
fi

exit $RESULT
